catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index , name='index'),
    path('books', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book'),
    path('authors', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid





class Genre(models.Model):
    name = models.CharField(max_length=20, help_text='Enter the Book Genre Please')

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'



class Book(models.Model):
    title = models.CharField(max_length=50, help_text='Enter the Book Title Please')
    isbn = models.CharField(
        'ISBN',max_length=13, 
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    genre = models.ManyToManyField(Genre, help_text='Please Select the Book Genre')
    summary = models.TextField(help_text='Enter a brief description of the Book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('book', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'




class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    # book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book Availability')

    class Meta:
        ordering = ['due_back']
    
    def __str__(self):
        return f'{self.id} (self.book.title)'

catalog/views.py
from django.shortcuts import render, HttpResponse
from django.views import generic
from .models import Book, BookInstance, Author, Genre



def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_available_instances = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.all().count()
    num_genres = Genre.objects.all().count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_available_instances': num_available_instances,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_visits': num_visits,
    }

    return render(request, 'catalog/index.html', context)




class BookListView(generic.ListView):
    model = Book
    # queryset = Book.objects.filter(title__icontains='django')
    context_object_name = 'book_list'
    template_name = 'catalog/book_listings.html'
    paginate_by = 2

    

class BookDetailView(generic.DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'catalog/book_detail.html'



class AuthorListView(generic.ListView):
    model = Author
    context_object_name = 'author_list'
    template_name = 'catalog/author_listings.html'




class AuthorDetailView(generic.DeleteView):
    model = Author
    context_object_name = 'author'
    template_name = 'catalog/author_detail.html'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
    <title>{% block title %}Saeed's Local Library{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% include 'partials/_sidebar.html' %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}
                        <!-- Body goes here and with other html pages we can overwrite the content block! -->
                {% endblock %}
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                                {% endif %}
                                <span class="page-current">
                                    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/catalog/author_detail.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <br>
    <h1>Author: {{ author.first_name }} {{author.last_name }} </h1>
    <div class="container">
        <p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>
    </div>
    <div style="margin-left:20px;margin-top:20px">
        <h4>Books:</h4>
        <dl>
            {% for book in author.book_set.all %}
            <dt><a href="{% url 'book' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
            <dd>{{book.summary}}</dd>
            {% endfor %}
        </dl>

    </div>
{% endblock %}

templates/catalog/author_listings.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br>
<br>
<h1>Author List:</h1>
<br>
<ul>
    {% if author_list %}
    {% for author in author_list %}
    <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
    </li>
    {% endfor %}
    {% else %}
    <h4>
        <p>There is no Author in our library!</p>
        <p>Come back later!</p>
    </h4>
    {% endif %}
</ul>
{% endblock %}

templates/catalog/book_detail.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
    <h1>Title: {{ book.title }}</h1>

    <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>

        <!-- https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views -->
        <!-- This method is "automatically" constructed by Django in order to return the set of BookInstance records associated with a particular Book -->
        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p
                class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

templates/catalog/book_listings.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <br>
    <br>
    <h1>Book List:</h1>
    <br>
    <ul>
        {% if book_list %}
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> | {{book.author}}
                </li>
            {% endfor %}
        {% else %}
            <h4><p>There is no book in our library!</p>
            <p>Come back later!</p></h4>
        {% endif %}
    </ul>
{% endblock %}

templates/catalog/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <br>
    <h1>Local Library Home Page</h1>
    <br>
    <h3>Welcome To <strong>Saeed's</strong> Library Fellas!</h3>
    <br>
    <h4>Library Contents:</h4>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{ num_available_instances }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
        <li><strong>Genres:</strong>{{ num_genres }}</li>
        <!-- <li><strong>Genres:</strong>{{ genres }}</li> -->
    </ul>
    <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}

templates/partials/_sidebar.html
{% load static %}

{% block sidebar %}
    <br>
    <ul class="sidebar-nav">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'books' %}">All books</a></li>
        <li><a href="{% url 'authors' %}">All Authors</a></li>
    </ul>
{% endblock %}